version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://84.46.249.121:8000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - SECRET_KEY=artutos123
      - ADMIN_EMAIL=admin@artutos.eu.org
      - ADMIN_PASSWORD=artutos123
      - DATA_FILE=/app/data/db.json