version: '3.8'

services:
  # Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    environment:
      - VITE_API_URL=http://api:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

  # Backend API Service
  api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/cookiemanager
      - JWT_SECRET=your-secret-key-here
      - CORS_ORIGIN=http://localhost
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  # Database Service
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cookiemanager
    volumes:
      - postgres_data:/data/postgres

  # Redis for Session Management
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: