version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    environment:
      - VITE_API_URL=http://84.46.249.121:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/cookiemanager
      - SECRET_KEY=your-secret-key-here
      - FRONTEND_URL=http://84.46.249.121
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cookiemanager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: