version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "31000:31000"  # Cambiado de expose a ports para permitir acceso directo
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://backend:8000
      - SECRET_KEY=dev-secret-key
      - ALLOWED_HOSTS=admin.artutos.us.kg
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Cambiado de expose a ports
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - SECRET_KEY=artutos123
      - ADMIN_EMAIL=admin@artutos.eu.org
      - ADMIN_PASSWORD=artutos123
      - DATA_FILE=/app/data/db.json
      - CORS_ORIGINS=https://admin.artutos.us.kg
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge