version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "31000:31000"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://backend:8000
      - SECRET_KEY=dev-secret-key
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - SECRET_KEY=artutos123
      - ADMIN_EMAIL=admin@artutos.eu.org
      - ADMIN_PASSWORD=artutos123
      - DATA_FILE=/app/data/db.json

volumes:
  data: